### ISSUE TITLE
why Decryption failed？

### ISSUE THREAD

**Issue by nobut** [surge-networks/snell#2]
2019-02-15 17:25:26.193376 [server_tunnel-3] <WARN> Decryption failed

**Comment by wenxingxing** [comment]
2019-02-15 09:15:50.527565 [server_tunnel-110] <WARN> Obfs decode failed

**Comment by primovist** [comment]
The same problem

**Comment by xiang510** [comment]
Me too,  I can’t understand 4th step.  Is it not inner config file?

**Comment by nobut** [comment]
我的解决了就是psk的问题，删除配置重新使用--wizard就好了

**Comment by nobut** [comment]
删除配置文件，使用--wizard重新生成配置文件就好了
