### ISSUE TITLE
snell.service: main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by aihui1983** [surge-networks/snell#29]
I have a server running snell-server v2.0.0b,  but snell.service will report an error and exit after a while.Can you please help me troubleshooting what is going on?

cat /etc/redhat-release:
CentOS Linux release 7.6.1810 (Core) 

uname -r:
5.5.10-1.el7.elrepo.x86_64

systemctl status snell -l:
                                                         
● snell.service - Snell Proxy Service
   Loaded: loaded (/etc/systemd/system/snell.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Sun 2020-03-22 06:03:44 UTC; 1h 14min ago
  Process: 4208 ExecStart=/usr/local/bin/snell-server -c /etc/snell/snell-server.conf (code=killed, signal=SEGV)
 Main PID: 4208 (code=killed, signal=SEGV)

Mar 22 05:04:40 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:40.100981 [server_tunnel-8700] <WARN> Outgoing connection connect error connection refused
Mar 22 05:07:15 myIPv6VM0 snell-server[4208]: 2020-03-22 05:07:15.631466 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:25:10 myIPv6VM0 snell-server[4208]: 2020-03-22 05:25:10.741567 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:25:12 myIPv6VM0 snell-server[4208]: 2020-03-22 05:25:11.999771 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:26:14 myIPv6VM0 snell-server[4208]: 2020-03-22 05:26:14.333170 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:29:25 myIPv6VM0 snell-server[4208]: 2020-03-22 05:29:25.378310 [server_tunnel-9743] <WARN> Write error: broken pipe, outgoing_socket: 1
Mar 22 05:50:34 myIPv6VM0 snell-server[4208]: 2020-03-22 05:50:34.208352 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 06:03:44 myIPv6VM0 systemd[1]: snell.service: main process exited, code=killed, status=11/SEGV
Mar 22 06:03:44 myIPv6VM0 systemd[1]: Unit snell.service entered failed state.
Mar 22 06:03:44 myIPv6VM0 systemd[1]: snell.service failed.

journalctl -xe:

ar 22 05:04:37 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:37.799988 [server_tunnel-8497] <WARN> Outgoing connect
Mar 22 05:04:38 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:38.361075 [server_tunnel-8696] <WARN> Outgoing connect
Mar 22 05:04:38 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:38.738121 [server_tunnel-8697] <WARN> Outgoing connect
Mar 22 05:04:39 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:39.200397 [server_tunnel-8698] <WARN> Outgoing connect
Mar 22 05:04:39 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:39.604698 [server_tunnel-8699] <WARN> Outgoing connect
Mar 22 05:04:40 myIPv6VM0 snell-server[4208]: 2020-03-22 05:04:40.100981 [server_tunnel-8700] <WARN> Outgoing connect
Mar 22 05:07:15 myIPv6VM0 snell-server[4208]: 2020-03-22 05:07:15.631466 [server_tunnel-0] <ERR> shutdown failed: ECANCELED

Mar 22 05:25:10 myIPv6VM0 snell-server[4208]: 2020-03-22 05:25:10.741567 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:25:12 myIPv6VM0 snell-server[4208]: 2020-03-22 05:25:11.999771 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:26:14 myIPv6VM0 snell-server[4208]: 2020-03-22 05:26:14.333170 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 05:29:25 myIPv6VM0 snell-server[4208]: 2020-03-22 05:29:25.378310 [server_tunnel-9743] <WARN> Write error: broken pipe, outgoing_socket: 1

Mar 22 06:03:44 myIPv6VM0 kernel: snell-server[4208]: segfault at 238 ip 0000000000407794 sp 00007ffc0
Mar 22 06:03:44 myIPv6VM0 kernel: Code: 78 04 5b c3 66 90 89 df e8 e9 bc 00 00 5b 48 89 c1 ba f5 b4 44
Mar 22 06:03:44 myIPv6VM0 systemd[1]: snell.service: main process exited, code=killed, status=11/SEGV
Mar 22 06:03:44 myIPv6VM0 systemd[1]: Unit snell.service entered failed state.
Mar 22 06:03:44 myIPv6VM0 systemd[1]: snell.service failed.

**Comment by surge-networks** [comment]
Please try the beta 2 version to confirm whether the crash has been eliminated. Thanks

**Comment by aihui1983** [comment]
> Please try the beta 2 version to confirm whether the crash has been eliminated. Thanks

beta2 still report an error and exit:

systemctl status snell -l 
● snell.service - Snell Proxy Service
   Loaded: loaded (/etc/systemd/system/snell.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Sun 2020-03-22 14:55:38 UTC; 1min 52s ago
  Process: 4195 ExecStart=/usr/local/bin/snell-server -c /etc/snell/snell-server.conf (code=killed, signal=ABRT)
 Main PID: 4195 (code=killed, signal=ABRT)

Mar 22 13:41:26 myIPv6VM0 snell-server[4195]: 2020-03-22 13:41:26.183596 [server_tunnel-4655] <WARN> Outgoing connection connect error connection timed out
Mar 22 13:41:34 myIPv6VM0 snell-server[4195]: 2020-03-22 13:41:34.375530 [server_tunnel-4657] <WARN> Outgoing connection connect error connection timed out
Mar 22 14:04:06 myIPv6VM0 snell-server[4195]: 2020-03-22 14:04:06.869103 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 14:16:35 myIPv6VM0 snell-server[4195]: 2020-03-22 14:16:35.623515 [server_tunnel-5128] <WARN> Incoming socket read error: ETIMEDOUT
Mar 22 14:17:45 myIPv6VM0 snell-server[4195]: 2020-03-22 14:17:45.255494 [server_tunnel-6773] <WARN> Outgoing connection connect error connection timed out
Mar 22 14:21:05 myIPv6VM0 snell-server[4195]: 2020-03-22 14:21:05.959484 [server_tunnel-6030] <WARN> Incoming socket read error: ETIMEDOUT
Mar 22 14:55:38 myIPv6VM0 snell-server[4195]: snell-server: /root/hyperway-server/src/server/sn_server_tunnel.c:430: shutdown_outgoing_connection: Assertion `ctx->outgoing_socket_stage == SN_SERVER_TUNNEL_OUTGOING_CONNECTION_STAGE_CONNECTED || ctx->outgoing_socket_stage == SN_SERVER_TUNNEL_OUTGOING_CONNECTION_STAGE_READ_CLOSE' failed.
Mar 22 14:55:38 myIPv6VM0 systemd[1]: snell.service: main process exited, code=killed, status=6/ABRT
Mar 22 14:55:38 myIPv6VM0 systemd[1]: Unit snell.service entered failed state.
Mar 22 14:55:38 myIPv6VM0 systemd[1]: snell.service failed.

**Comment by linsfg** [comment]
beta2 still report an error and exit:

Mar 22 07:19:10 adadad snell-server[4484]: 2020-03-22 07:19:10.444245 [server_tunnel-3] <WARN> Incoming socket read error: ETIMEDOUT
Mar 22 07:28:43 adadad snell-server[4484]: 2020-03-22 07:28:43.884509 [server_tunnel-9] <WARN> Incoming socket read error: ETIMEDOUT
Mar 22 07:29:02 adadad snell-server[4484]: 2020-03-22 07:29:02.452672 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 22 07:32:49 adadad snell-server[4484]: 2020-03-22 07:32:49.644416 [server_tunnel-1] <WARN> Incoming socket read error: ETIMEDOUT
Mar 22 08:05:07 adadad snell-server[4484]: 2020-03-22 08:05:07.052228 [server_tunnel-108] <WARN> Outgoing connection connect error connection timed out
Mar 22 08:32:26 adadad snell-server[4484]: 2020-03-22 08:32:26.990045 [server_tunnel-153] <WARN> Write error: broken pipe, outgoing_socket: 1
Mar 22 08:37:36 adadad snell-server[4484]: snell-server: /root/hyperway-server/src/server/sn_server_tunnel.c:430: shutdown_outgoing_connection:...' failed.
Mar 22 08:37:36 adadad systemd[1]: snell.service: main process exited, code=killed, status=6/ABRT
Mar 22 08:37:36 adadad systemd[1]: Unit snell.service entered failed state.
Mar 22 08:37:36 adadad systemd[1]: snell.service failed.

**Comment by surge-networks** [comment]
Please try the beta 3 version.

**Comment by aihui1983** [comment]
> Please try the beta 3 version.

Beta3 still report an error and exit，here is the log output：

/usr/local/bin/snell-server -v：

2020-03-23 03:45:02.029058 [server_main] <NOTIFY> snell-server v2.0.0 (Mar 23 2020 00:14:02)

journalctl -xe：

Mar 23 03:07:24 myIPv6VM0 snell-server[12067]: 2020-03-23 03:07:24.912020 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 23 03:08:18 myIPv6VM0 kernel: snell-server[12067]: segfault at 10 ip 000000000041c954 sp 00007ffff8664990 error 4 in snell-server[400000+64000]
Mar 23 03:08:18 myIPv6VM0 kernel: Code: 15 66 83 fa 0a 74 0f 66 83 fa 01 ba 07 00 00 00 0f 44 c2 eb 87 90 b8 0c 00 00 00 e9 7c ff ff ff 66 0f 1f 44 00 00 48 83 ec 08 <8b> 4e 10 48 89 f
Mar 23 03:08:18 myIPv6VM0 systemd[1]: snell.service: main process exited, code=killed, status=11/SEGV
Mar 23 03:08:18 myIPv6VM0 systemd[1]: Unit snell.service entered failed state.
Mar 23 03:08:18 myIPv6VM0 systemd[1]: snell.service failed.

systemctl status snell -l：

● snell.service - Snell Proxy Service
   Loaded: loaded (/etc/systemd/system/snell.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Mon 2020-03-23 03:08:18 UTC; 32min ago
  Process: 12067 ExecStart=/usr/local/bin/snell-server -c /etc/snell/snell-server.conf (code=killed, signal=SEGV)
 Main PID: 12067 (code=killed, signal=SEGV)

Mar 22 23:36:18 myIPv6VM0 snell-server[12067]: 2020-03-22 23:36:18.727718 [server_tunnel-20874] <WARN> Outgoing connection connect error connection timed out
Mar 22 23:49:16 myIPv6VM0 snell-server[12067]: 2020-03-22 23:49:16.967565 [server_tunnel-21600] <WARN> Outgoing connection connect error connection timed out
Mar 23 00:39:19 myIPv6VM0 snell-server[12067]: 2020-03-23 00:39:19.335551 [server_tunnel-24366] <WARN> Outgoing connection connect error connection timed out
Mar 23 00:39:23 myIPv6VM0 snell-server[12067]: 2020-03-23 00:39:23.431551 [server_tunnel-24367] <WARN> Outgoing connection connect error connection timed out
Mar 23 00:41:01 myIPv6VM0 snell-server[12067]: 2020-03-23 00:41:01.735481 [server_tunnel-24235] <WARN> Outgoing connection connect error connection timed out
Mar 23 01:01:01 myIPv6VM0 snell-server[12067]: 2020-03-23 01:01:01.863499 [server_tunnel-25499] <WARN> Outgoing connection connect error connection timed out
Mar 23 03:07:24 myIPv6VM0 snell-server[12067]: 2020-03-23 03:07:24.912020 [server_tunnel-0] <ERR> shutdown failed: ECANCELED
Mar 23 03:08:18 myIPv6VM0 systemd[1]: snell.service: main process exited, code=killed, status=11/SEGV
Mar 23 03:08:18 myIPv6VM0 systemd[1]: Unit snell.service entered failed state.
Mar 23 03:08:18 myIPv6VM0 systemd[1]: snell.service failed.

**Comment by surge-networks** [comment]
@aihui1983 
Please append launch argument '-l verbose' to enable debug output. Thanks.

**Comment by aihui1983** [comment]
This issue has been fixed,thanks.
