### ISSUE TITLE
电脑和手机同时使用时服务端的service会停止，但两台手机没有问题

### ISSUE THREAD

**Issue by akw5454521** [surge-networks/snell#36]
电脑上用snell上网，没问题，但是如果手机端也开始用snell上网的话，大概10秒钟后就都连不上服务端了，客户端日志提示连接被拒绝，在服务端查看status，发现状态变为failure，截图在下边。用重启命令后又能正常使用了。反过来也是，手机上网没问题，再用电脑连的话，也是会很快failure
snell版本是2，电脑和手机用的是同一配置文件，连的是同一Wifi。后来尝试电脑Wifi手机走移动数据，情况和上边完全一样

然后另一台手机上也上了snell，两台手机同时用snell上网，没任何问题，无论是连同一Wifi还是Wifi/移动数据
不知道有没有大佬知道这是啥情况啊……

![捕获](https://user-images.githubusercontent.com/68607321/99298509-c6bcfb00-2884-11eb-857c-5dd27ec238d9.PNG)

**Comment by bryanwongxin** [comment]
我也遇到了同样的问题...

**Comment by surge-networks** [comment]
Please verify if the v2.0.4 fixes the issue. Thanks.

**Comment by akw5454521** [comment]
> Please verify if the v2.0.4 fixes the issue. Thanks.

This time the server lasts longer than old version, maybe several minutes, but turned into “failed” eventually. I suspect this was caused by my client on PC, so close this issue first. Thank you anyway 😸
