### ISSUE TITLE
snell server 周期性hang住无法使用

### ISSUE THREAD

**Issue by ekousp** [surge-networks/snell#37]
![image](https://user-images.githubusercontent.com/1320677/102747447-4154cb00-439b-11eb-95a6-b62f41500764.png)

你好，

snell server在使用过程中，会不定时地进入无法使用地状态，日志见上图。使用的协议是v2版，每次出现后重启就解决了。

请问如何解决？谢谢。

**Comment by surge-networks** [comment]
Please verify if the v2.0.4 fixes the issue. Thanks.
