### ISSUE TITLE
host is unreachable

### ISSUE THREAD

**Issue by KangKai1982** [surge-networks/snell#4]
[server_tunnel-1] <WARN> Outgoing connection connect error host is unreachable

客户端是 surge iOS 3.6.0 1262 beta
服务器端使用wizard建立了两次conf，运行后尝试连接，服务器端均有以上错误，无法连接

**Comment by Benny-F** [comment]
你用的是anyNode的灵车吗？禁用IPV6就好了。它没有ipv6路由。
