### ISSUE TITLE
listen on IPv6 and IPv4 interfaces simultaneously 

### ISSUE THREAD

**Issue by orisson003** [surge-networks/snell#46]
It’s good to see the new pre-release beta Snell now supports to listen on IPv6 interface. However, given most of the severs are not only IPv6 only but also dual-stack, it’s more practical to expect that Snell can listen on both interfaces for users to switch between IPv6 and v4. 

Local clients can use a simple policy group FALLBACK with a IPv6 only website to realise the auto-IPv6-IPv4 switch if the network environment supports only one. E.g.:

v6test = fallback, v6, v4, url = https://ipv6.vm3.test-ipv6.com/ip/?callback=?, interval = 3600

Now the issues hands to Snell’s support on listening on both interfaces. Currently, the syntax in Snell configured file listen = ::0,port, 0.0.0.0, port only permits to listen to v4.

**Comment by surge-networks** [comment]
You may start two snell-server instances with two configs for IPv4 and IPv6.

In fact, supporting listening on both v4 and v6 addresses natively shares the same logic as running a second process essentially.
