### ISSUE TITLE
release中v2.0.5的linux amd64的zip包的下载链接格式中怎么少了个v？导致调用失败了

### ISSUE THREAD

**Issue by Flygar** [surge-networks/snell#48]
https://github.com/surge-networks/snell/releases/download/2.0.5/snell-server-v2.0.5-linux-amd64.zip   第一个2.0.5前面没v
https://github.com/surge-networks/snell/releases/download/v2.0.6/snell-server-v2.0.6-linux-amd64.zip
https://github.com/surge-networks/snell/releases/download/v2.0.4/snell-server-v2.0.4-linux-amd64.zip

**Comment by surge-networks** [comment]
Fixed.
