### ISSUE TITLE
client "Failed to parse remote resource date " when config version=3

### ISSUE THREAD

**Issue by onlyxxp** [surge-networks/snell#53]
surge serv v3.0.0b2
[snell-server]
listen = ::0:2048
ipv6 = false
psk = key
obfs = tls
obfs-host = updates.cdn-apple.com
tfo = true
version = 3

surge client 4.10.0
【 "Failed to parse remote resource date "  】
snell = snell, 1.2.3.4, 2048, psk=key, obfs=tls, obfs-host=updates.cdn-apple.com, version=3, tfo=true, encrypt-method=AES-128-GCM
【version=2 is ok：】
snell = snell, 1.2.3.4, 2048, psk=key, obfs=tls, obfs-host=updates.cdn-apple.com, version=2, tfo=true, encrypt-method=AES-128-GCM

**Comment by surge-networks** [comment]
You need upgrade Surge to the latest beta version first.
