### ISSUE TITLE
Snell 好像出问题了

### ISSUE THREAD

**Issue by loyio** [surge-networks/snell#59]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/32695256/153597702-8ac80e71-022b-4779-aa9f-a8d6a7120de1.png">

```
Feb 11 06:47:17 ***.cloud snell[19421]: 2022-02-11 06:47:17.545038 [server_tunnel-114415] <WARN> Obfs decode failed
```

重启后还是不行

**Comment by steveshi** [comment]
没错，我也是这个问题

**Comment by sidkang** [comment]
```
2022-02-12 02:48:55.829413 [server_tunnel-1160] <WARN> DNS error: 11
2022-02-12 02:48:56.005017 [server_tunnel-1161] <WARN> DNS error: 11
2022-02-12 02:48:56.179394 [server_tunnel-1163] <WARN> DNS error: 11
2022-02-12 02:48:56.351105 [server_tunnel-1164] <WARN> DNS error: 11
2022-02-12 02:48:56.532828 [server_tunnel-1165] <WARN> DNS error: 11
2022-02-12 02:49:55.774730 [server_tunnel-1221] <WARN> Obfs decode failed
2022-02-12 02:49:55.988994 [server_tunnel-1222] <WARN> Obfs decode failed
2022-02-12 02:49:56.173093 [server_tunnel-1223] <WARN> Obfs decode failed
2022-02-12 02:49:56.350187 [server_tunnel-1224] <WARN> Obfs decode failed
2022-02-12 02:49:56.539626 [server_tunnel-1225] <WARN> Obfs decode failed
2022-02-12 02:49:56.739099 [server_tunnel-1226] <WARN> Obfs decode failed
2022-02-12 02:49:56.952631 [server_tunnel-1227] <WARN> Obfs decode failed
2022-02-12 02:49:57.133700 [server_tunnel-1228] <WARN> Obfs decode failed
```

同样的问题

**Comment by wbconnie** [comment]
[我的snell2也是，更新成3就好了
<img width="337" alt="CleanShot 2022-02-12 at 10 55 09@2x" src="https://user-images.githubusercontent.com/49267586/153694049-ac53d8ae-7876-4851-bd76-3f158a3d1308.png">

**Comment by wbconnie** [comment]
> [我的snell2也是，更新成3就好了 <img alt="CleanShot 2022-02-12 at 10 55 09@2x" width="337" src="https://user-images.githubusercontent.com/49267586/153694049-ac53d8ae-7876-4851-bd76-3f158a3d1308.png">
<img width="192" alt="CleanShot 2022-02-12 at 10 57 07@2x" src="https://user-images.githubusercontent.com/49267586/153694076-fe377dab-91e4-4ada-a812-21e7dee2b7c1.png">

**Comment by loyio** [comment]
> [我的snell2也是，更新成3就好了 <img alt="CleanShot 2022-02-12 at 10 55 09@2x" width="337" src="https://user-images.githubusercontent.com/49267586/153694049-ac53d8ae-7876-4851-bd76-3f158a3d1308.png">

我用的就是3

**Comment by loyio** [comment]
> > [我的snell2也是，更新成3就好了 <img alt="CleanShot 2022-02-12 at 10 55 09@2x" width="337" src="https://user-images.githubusercontent.com/49267586/153694049-ac53d8ae-7876-4851-bd76-3f158a3d1308.png">
> 
> <img alt="CleanShot 2022-02-12 at 10 57 07@2x" width="192" src="https://user-images.githubusercontent.com/49267586/153694076-fe377dab-91e4-4ada-a812-21e7dee2b7c1.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/32695256/153694130-bd193407-0ac1-4042-ae96-8f99d6c16835.png">
是改这里吗，没什么用

**Comment by steveshi** [comment]
> [我的snell2也是，更新成3就好了
> <img alt="CleanShot 2022-02-12 at 10 55 09@2x" width="337" src="https://user-images.githubusercontent.com/49267586/153694049-ac53d8ae-7876-4851-bd76-3f158a3d1308.png">

我就是最新的3.0.1，没用。估计2升3能用一段时间

**Comment by mpc2008cn** [comment]
同样问题,昨晚换了端口管用了一夜,今天又不行了
![image](https://user-images.githubusercontent.com/11917818/153704107-f8085bde-cb7d-4c41-b558-b021c540b947.png)

**Comment by sankely** [comment]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/22852977/153735541-1a5573ba-add6-4ce0-86e1-99ac3d26e575.png">
相同的问题，这几天才出现的，试了很多方法都一样

**Comment by STARTOKEN-LAB** [comment]
![image](https://user-images.githubusercontent.com/69802541/153753729-76f512a8-b090-4cb6-ad29-8b884eb51020.png)
昨天出现的，难道流量特征被识别了

**Comment by xsnaruto** [comment]
最近的几个版本都尝试了，差不多 1 分钟左右之后就会停止运行。蹲个结果～

**Comment by lostz** [comment]
snell 被墙了

**Comment by surge-networks** [comment]
可尝试修改 obfs 为 tls 模式

**Comment by loyio** [comment]
> 可尝试修改 obfs 为 tls 模式

你这也不能这么直接就close我们的issues，问题都还没解决呢。

**Comment by STARTOKEN-LAB** [comment]
> > 可尝试修改 obfs 为 tls 模式
> 
> 
> 
> 你这也不能这么直接就close我们的issues，问题都还没解决呢。

是tls 模式 还是报错呢
