### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by OraculaSibyllina** [surge-networks/snell#6]
Snell-server embeddeds libuv and libsodium into the binary. The licenses of both [libuv](https://github.com/libuv/libuv/blob/v1.x/LICENSE) and [libsodium](https://github.com/jedisct1/libsodium/blob/master/LICENSE) require to contain a copy of their license or copyright notice with EVERY copy of the software that uses them, which snell-server didn't do.

See:
https://github.com/libuv/libuv/blob/v1.x/LICENSE#L13-L14
https://github.com/jedisct1/libsodium/blob/master/LICENSE#L7-L9

**Comment by surge-networks** [comment]
Thanks for feedback. We have included all the license information in v1.0.1 by adding a '--license' option.
