### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by xiang510** [surge-networks/snell#7]
I can’t understand 4th step. Is it not inner config file?

**Comment by xiang510** [comment]
2019-02-19 14:39:28.775770 [server_main] <ERR> Failed to increase file descriptor limit: Invalid argument

**Comment by nobut** [comment]
第一次执行会有一个提示选Yes生成配置文件
![image](https://user-images.githubusercontent.com/28843198/53000226-d8306380-3462-11e9-8386-3d54f53d51ee.png)
